experiment_name: 3dcnn_adni_dl_finetune
dataset: adni
model: 3dcnn
trainer: dl
task: label
mode: finetune
num_classes: 3

processed_dir: dataset/processed_3dcnn/ADNI
metadata_csv: dataset/processed_3dcnn/ADNI/metadata.csv
checkpoint_path: 3D_CNN_pretrained_model/AD_pretrained_weights.pt
output_dir: outputs

batch_size: 4
epochs: 100
lr_head: 0.001
lr_backbone: 0.00001
weight_decay: 0.0001
dropout: 0.5
freeze_batchnorm: true
num_workers: 2
seed: 42
num_folds: 5
device: cuda
gpu_id: 1
load_pretrained: true