experiment_name: brainiac_ukb_finetune
dataset: ukb
model: brainiac
trainer: dl
mode: finetune
task: joint

processed_dir: dataset/processed_brainiac/UKB
metadata_csv: dataset/processed_brainiac/UKB/metadata.csv
brainiac_repo: BrainIAC
checkpoint_path: models/BrainIAC.ckpt
output_dir: outputs

image_size: [96, 96, 96]
batch_size: 1
epochs: 20
lr_head: 0.001
lr_backbone: 0.00001
weight_decay: 0
dropout: 0
num_workers: 2
seed: 42
num_folds: 5
device: cuda
gpu_id: 1

age_standardize: true
age_loss_weight: 1.0
sex_loss_weight: 1.0
