experiment_name: rootstrap_adni_baseline
dataset: adni
model: rootstrap
trainer: baseline
task: label
mode: pretrained_eval

processed_dir: dataset/processed_rootstrap/ADNI
metadata_csv: dataset/processed_rootstrap/ADNI/metadata.csv
output_dir: outputs
checkpoint_path: models/Alzheimer-Classifier-Demo/86_acc_model.pth
rootstrap_input_shape: [96, 96, 96]

seed: 42
dropout: 0
batch_size: 2
num_workers: 2
device: cuda
gpu_id: 0
