experiment_name: sfcn_ukb_age_finetune_data_aug_3
dataset: ukb
model: sfcn
trainer: dl
task: age
mode: finetune
processed_dir: dataset/processed_sfcn/UKB
metadata_csv: dataset/processed_sfcn/UKB/metadata.csv
output_dir: outputs
sfcn_repo: UKBiobank_deep_pretrain
sfcn_input_shape: [160, 192, 160]
checkpoint_path: UKBiobank_deep_pretrain/brain_age/run_20190719_00_epoch_best_mae.p
pretrained_task: age
use_pretrained_head: true
extract_features: false
load_pretrained: true
seed: 42
num_folds: 5
batch_size: 1
epochs: 30
lr: 0.00001
lr_backbone: 0.00001
weight_decay: 1e-4
dropout: true
data_augment:
  enabled: true
  separate_transforms: true
  multiplier: 3
  separate_transform_names: [zoom, shift, rotation]
  shift_voxels: 5
  rotate_degrees: 8
  scale_range: [0.95, 1.05]
num_workers: 2
device: cuda
gpu_id: 1
