experiment_name: rootstrap_adni_finetune
dataset: adni
model: rootstrap
trainer: dl
task: label
mode: finetune
num_classes: 3

processed_dir: dataset/processed_rootstrap/ADNI
metadata_csv: dataset/processed_rootstrap/ADNI/metadata.csv
output_dir: outputs
checkpoint_path: models/Alzheimer-Classifier-Demo/86_acc_model.pth
rootstrap_input_shape: [96, 96, 96]

seed: 42
num_folds: 5
batch_size: 1
epochs: 50
lr: 0.0001
weight_decay: 0
freeze_batchnorm: true
data_augment:
  enabled: false
num_workers: 2
device: cuda
gpu_id: 0
