experiment_name: sfcn_ukb_sex_baseline
dataset: ukb
model: sfcn
trainer: dl
task: sex
mode: pretrained_eval
processed_dir: dataset/processed_sfcn/UKB
metadata_csv: dataset/processed_sfcn/UKB/metadata.csv
output_dir: outputs
sfcn_repo: UKBiobank_deep_pretrain
sfcn_input_shape: [160, 192, 160]
checkpoint_path: UKBiobank_deep_pretrain/sex_prediction/run_20191008_00_epoch_last.p
pretrained_task: sex
use_pretrained_head: true
extract_features: false
seed: 42
num_folds: 5
batch_size: 1
epochs: 0
lr: 0.00001
lr_backbone: 0.000001
weight_decay: 0
dropout: true
data_augment: false
num_workers: 2
device: cuda
gpu_id: 3
